import SwiftUI

// Generated by Supernova - do not modify manually
extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // Light
        let lightOrange = Color(.sRGB, red: 247/255, green: 147/255, blue: 26/255, opacity: 1) 
        let lightRed = Color(.sRGB, red: 235/255, green: 87/255, blue: 87/255, opacity: 1) 
        let lightGreen = Color(.sRGB, red: 39/255, green: 174/255, blue: 96/255, opacity: 1) 
        let lightBlue = Color(.sRGB, red: 45/255, green: 156/255, blue: 219/255, opacity: 1) 
        let lightPurple = Color(.sRGB, red: 187/255, green: 107/255, blue: 217/255, opacity: 1) 
        let lightForeground = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        let lightNeutral840Cc = Color(.sRGB, red: 64/255, green: 64/255, blue: 64/255, opacity: 1) 
        let lightNeutral777176 = Color(.sRGB, red: 119/255, green: 119/255, blue: 119/255, opacity: 1) 
        let lightNeutral699148 = Color(.sRGB, red: 153/255, green: 153/255, blue: 153/255, opacity: 1) 
        let lightNeutral5Bb120 = Color(.sRGB, red: 187/255, green: 187/255, blue: 187/255, opacity: 1) 
        let lightNeutral4De92 = Color(.sRGB, red: 222/255, green: 222/255, blue: 222/255, opacity: 1) 
        let lightNeutral3Ed64 = Color(.sRGB, red: 237/255, green: 237/255, blue: 237/255, opacity: 1) 
        let lightNeutral2F445 = Color(.sRGB, red: 244/255, green: 244/255, blue: 244/255, opacity: 1) 
        let lightNeutral1F826 = Color(.sRGB, red: 248/255, green: 248/255, blue: 248/255, opacity: 1) 
        let lightBackground = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // Dark
        let darkForeground = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let darkNeutral840Cc = Color(.sRGB, red: 204/255, green: 204/255, blue: 204/255, opacity: 1) 
        let darkNeutral777176 = Color(.sRGB, red: 176/255, green: 176/255, blue: 176/255, opacity: 1) 
        let darkNeutral699148 = Color(.sRGB, red: 148/255, green: 148/255, blue: 148/255, opacity: 1) 
        let darkNeutral5Bb120 = Color(.sRGB, red: 120/255, green: 120/255, blue: 120/255, opacity: 1) 
        let darkNeutral4De92 = Color(.sRGB, red: 92/255, green: 92/255, blue: 92/255, opacity: 1) 
        let darkNeutral3Ed64 = Color(.sRGB, red: 68/255, green: 68/255, blue: 68/255, opacity: 1) 
        let darkNeutral2F445 = Color(.sRGB, red: 45/255, green: 45/255, blue: 45/255, opacity: 1) 
        let darkNeutral1F826 = Color(.sRGB, red: 26/255, green: 26/255, blue: 26/255, opacity: 1) 
        let darkBackground = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        let darkPurple = Color(.sRGB, red: 192/255, green: 117/255, blue: 220/255, opacity: 1) 
        let darkBlue = Color(.sRGB, red: 60/255, green: 163/255, blue: 222/255, opacity: 1) 
        let darkGreen = Color(.sRGB, red: 54/255, green: 180/255, blue: 107/255, opacity: 1) 
        let darkRed = Color(.sRGB, red: 236/255, green: 99/255, blue: 99/255, opacity: 1) 
        let darkOrange = Color(.sRGB, red: 248/255, green: 155/255, blue: 42/255, opacity: 1) 
    }
}