import SwiftUI

// Generated by Supernova - do not modify manually
extension Text {

    func textStyleAnnotationTitle1() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 36))
    }

    func textStyleAnnotationText() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 22))
    }

    func textStyleTitle136() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 36))
    }

    func textStyleTitle228() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 28))
    }

    func textStyleTitle324() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 24))
    }

    func textStyleTitle421() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 21))
    }

    func textStyleTitle518() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 18))
    }

    func textStyleBody124() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 24))
    }

    func textStyleBody221() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 21))
    }

    func textStyleBody318() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 18))
    }

    func textStyleBody318Numbers() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 18))
    }

    func textStyleBody415() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 15))
    }

    func textStyleBody415Numbers() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 15))
    }

    func textStyleBody513() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 13))
    }
}
